# TypeProf 0.21.3

# Classes
module CrypticResolver
  GEM_VERSION: String

  class Resolver
    DEFAULT_LIB_PATH: String
    ORIGINAL_DEFAULT_DICTS: [String, String, String, String, String]
    RECOMMENDED_DICTS: String

    def bold: (untyped str) -> String
    def underline: (untyped str) -> String
    def red: (untyped str) -> String
    def green: (untyped str) -> String
    def yellow: (untyped str) -> String
    def blue: (untyped str) -> String
    def purple: (untyped str) -> String
    def cyan: (untyped str) -> String
    attr_accessor def_dicts: [String, String, String, String, String]
    attr_accessor extra_lib_path: nil
    attr_accessor counter: Counter
    def initialize: -> void
    def is_there_any_dict?: -> bool
    def add_default_dicts_if_none_exists: -> bool

    class Counter
      attr_accessor word_count_of_two_libs: Integer
      attr_accessor word_count_of_def_lib: Integer
      attr_accessor word_count_of_extra_lib: Integer
      def initialize: -> void
      def count_dict_words: (untyped library, untyped dict) -> (Complex | Float | Integer | Rational)
    end
  end
end
