#!/usr/bin/env ruby
# ------------------------------------------------------
# File          : cr.rb
# Authors       : Aoran Zeng <ccmywish@qq.com>
# Created on    : <2021-07-08>
# Last modified : <2023-05-14>
#
# cr:
#
#   This file is used to explain a CRyptic command
# or an acronym's real meaning in computer world or
# other fields.
# ------------------------------------------------------

require 'cr'

module CrypticResolver::CLI

  def self.run
    args = ARGV.dup

    option = args.shift

    case option when nil, '-h','--help' then help; exit end

    reslvr = CrypticResolver::Resolver.new

    reslvr.add_default_dicts_if_none_exists

    case option
    when '-l'   then reslvr.list_dicts
    when '-c'   then reslvr.count_words
    when '-u'   then reslvr.update_dicts
    when '-s'   then reslvr.search_related_words args.shift
    when '-a'   then reslvr.add_dict             args.shift
    when '-d'   then reslvr.del_dict             args.shift
    else             reslvr.resolve_word         option
    end
  end


  def self.help
    puts <<~HELP
    cr: Cryptic Resolver v#{CrypticResolver::GEM_VERSION}

    Usage:
      cr <keyword>   Search the keyword
      cr emacs       => Edit macros: A feature-rich editor

    Options:
      -c             Print word count
      -s <pattern>   Search words matched with pattern
      -h             Print this help

    Dictionaries:
      -l                      List local dicts and official dicts
      -u                      Update all dicts in Default library
      -a <https://repo[.git]> Add a new dict
      -a <user/repo>          Add a new dict from Github
      -a <dict_name>          Add an official dict, use -l to see
      -d <dict_name>          Delete a dict

    HELP
  end

end

CrypticResolver::CLI.run
