name: My workflow
on: 
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '55 9 * * *' # everyday 1 +8 = 9 in CST
jobs:
  Update-Readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Check out another repo
      uses: actions/checkout@v2
      with:
        repository: "cryptic-resolver/cryptic_computer"
    - name: Update word counts in README
      run: | # Try gem install again, because require error; Not use bundle 
        gem install tomlrb
        rake uwc
    - name: Git commit
      run: |
        git config --local user.email "ccmywish@qq.com"
        git config --local user.name "ccmywish"
        git add README.md
        git commit -m "update word counts"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.MY_GIT_TOKEN }}
        branch: main