name: uwc

on:
  [push]
  #schedule:
  #  - cron:  '0 1 * * 1'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Install default dictionaries
      run: bundle exec ./bin/cr
    - name: uwc
      run: 
        bundle exec ./bin/wc
    - name: Git commit
      run: |
        git config --local user.email "ccmywish@qq.com"
        git config --local user.name "ccmywish"
        git add README.md
        git commit -m "Update word counts in README"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.MY_GIT_TOKEN }}
        branch: main
